=== j-dornbusch/scolomfr-recette/src/main/resources/scolomfr/scolomfr-v-3-1/XML/Dtd-Nomenclature.dtd
<?xml version="1.0" encoding ="ISO-8859-1"?>
<!-- DTD des fichiers XML ScoLOMFR - Canopé 20/12/2016
MAJ : 
- mise à jour en fonction de la V3.1 ; 20/12/2016 Canopé
- vérification ; ajout REMPLACE PAR et STATUS par Canopé pour validation du fichier XML des concepts dépréciés du ScoLOMFR.
NOTES :
- déclarer par <!DOCTYPE NOMENCLATURE SYSTEM "Dtd-Nomenclature.dtd">
-->

<!ELEMENT NOMENCLATURE (CONCEPT+)>
<!ELEMENT CONCEPT (ID,DF*,NA*,ORDRE?,ORIGINE?,TERME+,TERME_TE*,REMPLACE_PAR?,STATUS?,TERME_TA*,TS*)>
<!ELEMENT TERME (INTITULE,ID)>
<!ELEMENT INTITULE (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT DF (#PCDATA)>
<!ELEMENT NA (#PCDATA)>
<!ELEMENT ORDRE (#PCDATA)>
<!ELEMENT ORIGINE (#PCDATA)>
<!ELEMENT TERME_TE (INTITULE,ID)>
<!ELEMENT REMPLACE_PAR (#PCDATA)>
<!ELEMENT STATUS (#PCDATA)>
<!ELEMENT TERME_TA (INTITULE,ID)>
<!ELEMENT TS (CONCEPT+)>

<!ATTLIST INTITULE lang CDATA "fr">
<!ATTLIST DF lang CDATA "fr">
<!ATTLIST NA lang CDATA "fr">
<!ATTLIST ORDRE lang CDATA "fr">

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-2-0/XML/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/draft</ID>
      <DF lang="fr">État de la ressource</DF>
      <NA lang="fr">Esquisse, ébauche d'une ressource destinée à être complétée, modifiée, enrichie... pour atteindre l'état final. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">brouillon</INTITULE>
         <ID>draft</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">brouillon</INTITULE>
         <ID>scolomfr-voc-002-num-001</ID>
      </TERME_TE>
      <TERME_TE>
         <INTITULE lang="fr">document de travail</INTITULE>
         <ID>scolomfr-voc-002-num-006</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/final</ID>
      <DF lang="fr">État de la ressource</DF>
      <NA lang="fr">État d'une ressource considérée alors dans sa version courante et qui peut dès lors être utilisée et diffusée. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">final</INTITULE>
         <ID>final</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">final</INTITULE>
         <ID>scolomfr-voc-002-num-002</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/unavailable</ID>
      <DF lang="fr">État de la ressource</DF>
      <NA lang="fr">État d'une ressource non disponible. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">indisponible</INTITULE>
         <ID>unavailable</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">indisponible</INTITULE>
      </TERME_TE>
      <TERME_TE>
         <ID>scolomfr-voc-002-num-004</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/revised</ID>
      <DF lang="fr">État de la ressource</DF>
      <NA lang="fr">État final d'une ressource mais dans une version corrigée, modifiée ou amendée par rapport à la version préliminaire. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">révisé</INTITULE>
         <ID>revised</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">révisé</INTITULE>
         <ID>scolomfr-voc-002-num-003</ID>
      </TERME_TE>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/src/main/resources/scolomfr/scolomfr-v-3-1/XML/scolomfrSkosXl_n_08.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-008-num-01</ID>
      <DF lang="fr">Niveau d'agrégation</DF>
      <NA lang="fr">Ressource indivisible. Fait référence à une ressource que l'on estime ne pouvant pas être fragmentée et qui pourra être exploitée dans des ressources pédagogiques de granularité plus élevée (2, 3 ou 4). Par exemple, une photo ou une fiche technique, un exercice unique, le support d'une leçon...</NA>
      <TERME>
         <INTITULE lang="fr">1 - Granule</INTITULE>
         <ID>scolomfr-voc-008-num-05</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">1</INTITULE>
         <ID>scolomfr-voc-008-num-01</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-008-num-02</ID>
      <DF lang="fr">Niveau d'agrégation</DF>
      <NA lang="fr">Ensemble d'objets d'apprentissage de niveau 1. Fait référence à une ressource pédagogique regroupant un ensemble d'objets pédagogiques ou fragments. Par exemple : une ressource présentant une leçon incluant une vidéo numérique et un exercice ; une ressource présentant un travail d'évaluation et composée des consignes et support d'exercices, ainsi que des corrections.</NA>
      <TERME>
         <INTITULE lang="fr">2 - Leçon</INTITULE>
         <ID>scolomfr-voc-008-voc-06</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">2</INTITULE>
         <ID>scolomfr-voc-008-num-02</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-008-num-03</ID>
      <DF lang="fr">Niveau d'agrégation</DF>
      <NA lang="fr">Ensemble d'objets d'apprentissage de niveau 2. Fait référence à une ressource rassemblant un ensemble d'objets de niveau d'agrégation supérieur. Par exemple : une ressource décrivant un cours composé de plusieurs leçons.</NA>
      <TERME>
         <INTITULE lang="fr">3 - Cours</INTITULE>
         <ID>scolomfr-voc-008-num-07</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">3</INTITULE>
         <ID>scolomfr-voc-008-num-03</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-008-num-04</ID>
      <DF lang="fr">Niveau d'agrégation</DF>
      <NA lang="fr">Ensemble d'objets d'apprentissage de niveau 3 (granularité la plus élevée dans ce modèle). Fait référence à une ressource rassemblant un ensemble d'objets de niveau d'agrégation la plus élevée. Par exemple : une ressource décrivant le programme d'enseignement menant à un diplôme ou certificat.</NA>
      <TERME>
         <INTITULE lang="fr">4 - Module</INTITULE>
         <ID>scolomfr-voc-008-num-08</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">4</INTITULE>
         <ID>scolomfr-voc-008-num-04</ID>
      </TERME_TE>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-1/XML/scolomfrSkosXl_n_35.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-035-num-003</ID>
      <DF lang="fr">Type accès concours</DF>
      <NA lang="fr">Les concours externes sont ouverts aux candidats justifiant de certains diplômes ou de l'accomplissement de certaines études.</NA>
      <TERME>
         <INTITULE lang="fr">concours externe</INTITULE>
         <ID>scolomfr-voc-035-num-008</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-035-num-002</ID>
      <DF lang="fr">Type accès concours</DF>
      <NA lang="fr">Le concours interne concerne le personnel de la fonction publique, sous certaines conditions.</NA>
      <TERME>
         <INTITULE lang="fr">concours interne</INTITULE>
         <ID>scolomfr-voc-035-num-007</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-035-num-004</ID>
      <DF lang="fr">Type accès concours</DF>
      <TERME>
         <INTITULE lang="fr">concours réservé</INTITULE>
         <ID>scolomfr-voc-035-num-009</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-035-num-005</ID>
      <DF lang="fr">Type accès concours</DF>
      <NA lang="fr">Le troisième concours est accessible, sans condition de diplôme, à toute personne pouvant justifier d'une expérience d'au moins cinq ans dans le secteur privé.</NA>
      <TERME>
         <INTITULE lang="fr">troisième concours</INTITULE>
         <ID>scolomfr-voc-035-num-010</ID>
      </TERME>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3/XML/25.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/difficult</ID>
<DF lang="fr">Difficulté</DF>
<NA lang="fr">Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">difficile</INTITULE>
<ID>difficult</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">difficile</INTITULE>
<ID>scolomfr-voc-025-num-004</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/medium</ID>
<DF lang="fr">Difficulté</DF>
<NA lang="fr">Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">moyen</INTITULE>
<ID>medium</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">moyen</INTITULE>
<ID>scolomfr-voc-025-num-003</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/easy</ID>
<DF lang="fr">Difficulté</DF>
<NA lang="fr">Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">facile</INTITULE>
<ID>easy</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">facile</INTITULE>
<ID>scolomfr-voc-025-num-002</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/very_difficult</ID>
<DF lang="fr">Difficulté</DF>
<NA lang="fr">Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">très difficile</INTITULE>
<ID>very difficult</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">très difficile</INTITULE>
<ID>scolomfr-voc-025-num-005</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/very_easy</ID>
<DF lang="fr">Difficulté</DF>
<TERME>
<INTITULE lang="fr">très facile</INTITULE>
<ID>very easy</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">très facile</INTITULE>
<ID>scolomfr-voc-025-num-001</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/difficult</ID>
<DF lang="fr">Difficulté</DF>
<NA lang="fr">Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">difficile</INTITULE>
<ID>difficult</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">difficile</INTITULE>
<ID>scolomfr-voc-025-num-004</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/easy</ID>
<DF lang="fr">Difficulté</DF>
<NA lang="fr">Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">facile</INTITULE>
<ID>easy</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">facile</INTITULE>
<ID>scolomfr-voc-025-num-002</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/medium</ID>
<DF lang="fr">Difficulté</DF>
<NA lang="fr">Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">moyen</INTITULE>
<ID>medium</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">moyen</INTITULE>
<ID>scolomfr-voc-025-num-003</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/very_easy</ID>
<DF lang="fr">Difficulté</DF>
<TERME>
<INTITULE lang="fr">très facile</INTITULE>
<ID>very easy</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">très facile</INTITULE>
<ID>scolomfr-voc-025-num-001</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/very_difficult</ID>
<DF lang="fr">Difficulté</DF>
<NA lang="fr">Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">très difficile</INTITULE>
<ID>very difficult</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">très difficile</INTITULE>
<ID>scolomfr-voc-025-num-005</ID>
</TERME_TE>
</CONCEPT>
</NOMENCLATURE>
