=== j-dornbusch/scolomfr-recette/src/main/resources/scolomfr/scolomfr-v-3-1/XML/Dtd-Nomenclature.dtd
<?xml version="1.0" encoding ="ISO-8859-1"?>
<!-- DTD des fichiers XML ScoLOMFR - Canopé 20/12/2016
MAJ : 
- mise à jour en fonction de la V3.1 ; 20/12/2016 Canopé
- vérification ; ajout REMPLACE PAR et STATUS par Canopé pour validation du fichier XML des concepts dépréciés du ScoLOMFR.
NOTES :
- déclarer par <!DOCTYPE NOMENCLATURE SYSTEM "Dtd-Nomenclature.dtd">
-->

<!ELEMENT NOMENCLATURE (CONCEPT+)>
<!ELEMENT CONCEPT (ID,DF*,NA*,ORDRE?,ORIGINE?,TERME+,TERME_TE*,REMPLACE_PAR?,STATUS?,TERME_TA*,TS*)>
<!ELEMENT TERME (INTITULE,ID)>
<!ELEMENT INTITULE (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT DF (#PCDATA)>
<!ELEMENT NA (#PCDATA)>
<!ELEMENT ORDRE (#PCDATA)>
<!ELEMENT ORIGINE (#PCDATA)>
<!ELEMENT TERME_TE (INTITULE,ID)>
<!ELEMENT REMPLACE_PAR (#PCDATA)>
<!ELEMENT STATUS (#PCDATA)>
<!ELEMENT TERME_TA (INTITULE,ID)>
<!ELEMENT TS (CONCEPT+)>

<!ATTLIST INTITULE lang CDATA "fr">
<!ATTLIST DF lang CDATA "fr">
<!ATTLIST NA lang CDATA "fr">
<!ATTLIST ORDRE lang CDATA "fr">

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3/XML/44.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-044-num-002</ID>
<DF lang="fr">Type de données à caractère personnel</DF>
<NA lang="fr">Les données transférées ne peuvent en aucun cas permettre d'identifier l'utilisateur ; pas un traitement de données à caractère personnel au sens de la loi Informatique et Libertés ; pas d'identification chez le fournisseur de service ; profilage faible. L'utilisateur n'est identifiable par aucun acteur de la chaîne de mise à disposition de la ressource.</NA>
<ORDRE>002-personnalisation faible</ORDRE>
<TERME>
<INTITULE lang="fr">personnalisation faible : les données transférées ne peuvent en aucun cas permettre d'identifier l'utilisateur</INTITULE>
<ID>scolomfr-voc-044-num-002</ID>
</TERME>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-044-num-003</ID>
<DF lang="fr">Type de données à caractère personnel</DF>
<NA lang="fr">Les données transférées ne permettent pas d'identifier directement l'utilisateur ; traitement de données à caractère personnel au sens de la loi Informatique et Libertés ; pas d'identification chez le fournisseur de service ; profilage possible. Les données transférées permettent l'identification de l'utilisateur via un tiers de confiance mais ne comportent pas d'élément de son état civil ou de sa vie privée.</NA>
<ORDRE>003-personnalisation moyenne</ORDRE>
<TERME>
<INTITULE lang="fr">personnalisation moyenne : les données transférées ne permettent pas d'identifier directement l'utilisateur</INTITULE>
<ID>scolomfr-voc-044-num-003</ID>
</TERME>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-044-num-001</ID>
<DF lang="fr">Type de données à caractère personnel</DF>
<NA lang="fr">Aucune transmission de donnée utilisateur ; pas un traitement de données à caractère personnel au sens de la loi Informatique et Libertés ; pas d'identification chez le fournisseur de service ; aucun profilage.</NA>
<ORDRE>001-personnalisation nulle</ORDRE>
<TERME>
<INTITULE lang="fr">personnalisation nulle : la seule donnée envoyée attachée à l'utilisateur est le code établissement</INTITULE>
<ID>scolomfr-voc-044-num-001</ID>
</TERME>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-044-num-004</ID>
<DF lang="fr">Type de données à caractère personnel</DF>
<NA lang="fr">Les données transférées permettent d'identifier directement l'individu et/ou comportent des éléments de son état civil ou de sa vie privée ; traitement de DCP au sens de la loi Informatique et Libertés ; identification possible chez le SP ; profilage possible sur les éléments d'état civil et/ou de vie privée.</NA>
<ORDRE>004-personnalisation forte</ORDRE>
<TERME>
<INTITULE lang="fr">personnalisation forte : les données transférées permettent d'identifier directement l'individu et/ou comportent des éléments de son état civil ou de sa vie privée</INTITULE>
<ID>scolomfr-voc-044-num-004</ID>
</TERME>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-044-num-001</ID>
<DF lang="fr">Type de données à caractère personnel</DF>
<NA lang="fr">Aucune transmission de donnée utilisateur ; pas un traitement de données à caractère personnel au sens de la loi Informatique et Libertés ; pas d'identification chez le fournisseur de service ; aucun profilage.</NA>
<ORDRE>001-personnalisation nulle</ORDRE>
<TERME>
<INTITULE lang="fr">personnalisation nulle : la seule donnée envoyée attachée à l'utilisateur est le code établissement</INTITULE>
<ID>scolomfr-voc-044-num-001</ID>
</TERME>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-044-num-002</ID>
<DF lang="fr">Type de données à caractère personnel</DF>
<NA lang="fr">Les données transférées ne peuvent en aucun cas permettre d'identifier l'utilisateur ; pas un traitement de données à caractère personnel au sens de la loi Informatique et Libertés ; pas d'identification chez le fournisseur de service ; profilage faible. L'utilisateur n'est identifiable par aucun acteur de la chaîne de mise à disposition de la ressource.</NA>
<ORDRE>002-personnalisation faible</ORDRE>
<TERME>
<INTITULE lang="fr">personnalisation faible : les données transférées ne peuvent en aucun cas permettre d'identifier l'utilisateur</INTITULE>
<ID>scolomfr-voc-044-num-002</ID>
</TERME>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-044-num-003</ID>
<DF lang="fr">Type de données à caractère personnel</DF>
<NA lang="fr">Les données transférées ne permettent pas d'identifier directement l'utilisateur ; traitement de données à caractère personnel au sens de la loi Informatique et Libertés ; pas d'identification chez le fournisseur de service ; profilage possible. Les données transférées permettent l'identification de l'utilisateur via un tiers de confiance mais ne comportent pas d'élément de son état civil ou de sa vie privée.</NA>
<ORDRE>003-personnalisation moyenne</ORDRE>
<TERME>
<INTITULE lang="fr">personnalisation moyenne : les données transférées ne permettent pas d'identifier directement l'utilisateur</INTITULE>
<ID>scolomfr-voc-044-num-003</ID>
</TERME>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-044-num-004</ID>
<DF lang="fr">Type de données à caractère personnel</DF>
<NA lang="fr">Les données transférées permettent d'identifier directement l'individu et/ou comportent des éléments de son état civil ou de sa vie privée ; traitement de DCP au sens de la loi Informatique et Libertés ; identification possible chez le SP ; profilage possible sur les éléments d'état civil et/ou de vie privée.</NA>
<ORDRE>004-personnalisation forte</ORDRE>
<TERME>
<INTITULE lang="fr">personnalisation forte : les données transférées permettent d'identifier directement l'individu et/ou comportent des éléments de son état civil ou de sa vie privée</INTITULE>
<ID>scolomfr-voc-044-num-004</ID>
</TERME>
</CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-2-0/XML/26.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/no</ID>
      <DF lang="fr">Coût</DF>
      <NA lang="fr">Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">gratuit</INTITULE>
         <ID>scolomfr-voc-026-num-004</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">non</INTITULE>
         <ID>no</ID>
      </TERME_TE>
      <TERME_TE>
         <INTITULE lang="fr">non</INTITULE>
         <ID>scolomfr-voc-026-num-002</ID>
      </TERME_TE>
      <TERME_TE>
         <INTITULE lang="fr">freemium</INTITULE>
         <ID>scolomfr-voc-026-num-006</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-026-num-007</ID>
      <DF lang="fr">Coût</DF>
      <TERME>
         <INTITULE lang="fr">partiellement gratuit</INTITULE>
         <ID>scolomfr-voc-026-num-007</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/yes</ID>
      <DF lang="fr">Coût</DF>
      <NA lang="fr">Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">payant</INTITULE>
         <ID>scolomfr-voc-026-num-005</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">oui</INTITULE>
         <ID>scolomfr-voc-026-num-001</ID>
      </TERME_TE>
      <TERME_TE>
         <INTITULE lang="fr">oui</INTITULE>
         <ID>yes</ID>
      </TERME_TE>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-2-0/XML/23.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/browser</ID>
      <DF lang="fr">Type (technique)</DF>
      <NA lang="fr">Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">navigateur</INTITULE>
         <ID>browser</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">navigateur</INTITULE>
         <ID>scolomfr-voc-023-num-001</ID>
      </TERME_TE>
      <TERME_TA_EXT>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-024-num-028</TERME_TA_EXT>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/operating_system</ID>
      <DF lang="fr">Type (technique)</DF>
      <NA lang="fr">Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">système d'exploitation</INTITULE>
         <ID>operating system</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">système d'exploitation</INTITULE>
         <ID>scolomfr-voc-023-num-002</ID>
      </TERME_TE>
      <TERME_TA_EXT>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-024-num-031</TERME_TA_EXT>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-1/XML/scolomfrSkosXl_n_07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/atomic</ID>
      <DF lang="fr">Structure</DF>
      <NA lang="fr">Une ressource indivisible dans ce contexte d'utilisation. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">atomique</INTITULE>
         <ID>atomic</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">atomique</INTITULE>
         <ID>scolomfr-voc-007-num-001</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/collection_2</ID>
      <DF lang="fr">Structure</DF>
      <NA lang="fr">Un ensemble de ressources, sans relations définies entre elles. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">collection</INTITULE>
         <ID>collection</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">collection</INTITULE>
         <ID>scolomfr-voc-007-num-002</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/networked</ID>
      <DF lang="fr">Structure</DF>
      <NA lang="fr">Un ensemble de ressources en relation les unes avec les autres. La nature de la (des) relation(s) n'est pas définie. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">en réseau</INTITULE>
         <ID>networked</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">en réseau</INTITULE>
         <ID>scolomfr-voc-007-num-003</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/hierarchical</ID>
      <DF lang="fr">Structure</DF>
      <NA lang="fr">Un ensemble de ressources dont les relations peuvent être représentées par une structure arborescente. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">hiérarchique</INTITULE>
         <ID>hierarchical</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">hiérarchique</INTITULE>
         <ID>scolomfr-voc-007-num-004</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/linear</ID>
      <DF lang="fr">Structure</DF>
      <NA lang="fr">Un ensemble de ressources parfaitement ordonnées. Exemple : un ensemble de ressources associées par des relations "précédent" et "suivant". Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">linéaire</INTITULE>
         <ID>linear</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">linéaire</INTITULE>
         <ID>scolomfr-voc-007-num-005</ID>
      </TERME_TE>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-2-0/conceptsDeprecies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1139</ID>
      <DF lang="fr">Domaine d'enseignement</DF>
      <TERME>
         <INTITULE lang="fr">qualités physiques des matériaux (arts plastiques cycle 3)</INTITULE>
         <ID>scolomfr-voc-015-num-1139</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1135</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1140</ID>
      <DF lang="fr">Domaine d'enseignement</DF>
      <TERME>
         <INTITULE lang="fr">effets du geste et de l'instrument (arts plastiques cycle 3)</INTITULE>
         <ID>scolomfr-voc-015-num-1140</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1135</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1141</ID>
      <DF lang="fr">Domaine d'enseignement</DF>
      <TERME>
         <INTITULE lang="fr">matérialité et qualité de la couleur (arts plastiques cycle 3)</INTITULE>
         <ID>scolomfr-voc-015-num-1141</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1136</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-926</ID>
      <DF lang="fr">Domaine d'enseignement</DF>
      <TERME>
         <INTITULE lang="fr">manipuler des grandeurs (mathématiques cycle 2)</INTITULE>
         <ID>scolomfr-voc-015-num-926</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1826</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-928</ID>
      <DF lang="fr">Domaine d'enseignement</DF>
      <TERME>
         <INTITULE lang="fr">résoudre des problèmes impliquant des grandeurs et mesures (mathématiques cycle 2)</INTITULE>
         <ID>scolomfr-voc-015-num-928</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1827</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-938</ID>
      <DF lang="fr">Domaine d'enseignement</DF>
      <TERME>
         <INTITULE lang="fr">résoudre des problèmes (mathématiques cycle 3)</INTITULE>
         <ID>scolomfr-voc-015-num-3700</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-015-num-1828</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-020-num-013</ID>
      <DF lang="fr">Outil</DF>
      <TERME>
         <INTITULE lang="fr">didacticiel</INTITULE>
         <ID>scolomfr-voc-020-num-013</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-020-num-146</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-020-num-042</ID>
      <DF lang="fr">Outil</DF>
      <TERME>
         <INTITULE lang="fr">logiciel de recherche documentaire</INTITULE>
         <ID>scolomfr-voc-020-num-042</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-020-num-055</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-028-num-004</ID>
      <DF lang="fr">Objectif</DF>
      <NA lang="fr">Ne correspond pas à un vocabulaire du ScoLOMFR. Le concept sera déprécié à la V3.1 du ScoLOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">enseignement</INTITULE>
         <ID>scolomfr-voc-028-num-004</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-028-num-003</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-028-num-018</ID>
      <DF lang="fr">Objectif</DF>
      <NA lang="fr">Ne pas employer ce concept (voué à dépréciation lors de la V3.1). Vocabulaire seulement relatif à l'élément 5 du ScoLOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">modalité pédagogique</INTITULE>
         <ID>scolomfr-voc-028-num-018</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-028-num-032</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-045-num-001</ID>
      <DF lang="fr">Label</DF>
      <NA lang="fr">Concept à utiliser pour la description de la compatibilité technique avec les plateformes faisant partie du FARE.</NA>
      <TERME>
         <INTITULE lang="fr">FARE</INTITULE>
         <ID>scolomfr-voc-045-num-001</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/gar</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-num-0504</ID>
      <DF lang="fr">Champ disciplinaire</DF>
      <TERME>
         <INTITULE lang="fr">IDEN, inspecteur formateur</INTITULE>
         <ID>scolomfr-voc-num-0504</ID>
      </TERME>
      <REMPLACE_PAR>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-014-num-2941</REMPLACE_PAR>
      <STATUS>Déprécié</STATUS>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-1/XML/scolomfrSkosXl_n_46.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-001</ID>
      <DF lang="fr">Type de distribution</DF>
      <TERME>
         <INTITULE lang="fr">en ligne</INTITULE>
         <ID>scolomfr-voc-046-num-001</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-002</ID>
      <DF lang="fr">Type de distribution</DF>
      <TERME>
         <INTITULE lang="fr">mode de distribution physique</INTITULE>
         <ID>scolomfr-voc-046-num-005</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-003</ID>
      <DF lang="fr">Type de distribution</DF>
      <TERME>
         <INTITULE lang="fr">téléchargeable</INTITULE>
         <ID>scolomfr-voc-046-num-003</ID>
      </TERME>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-2-0/XML/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/learner</ID>
      <DF lang="fr">Public cible</DF>
      <NA lang="fr">Personne qui exploite, travaille avec la ressource afin d'apprendre quelque chose. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">apprenant</INTITULE>
         <ID>learner</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">apprenant</INTITULE>
         <ID>scolomfr-voc-011-num-003</ID>
      </TERME_TE>
      <TERME_TA_EXT>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-021-num-0007</TERME_TA_EXT>
      <TERME_TA_EXT>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-021-num-0008</TERME_TA_EXT>
      <TERME_TA_EXT>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-021-num-0012</TERME_TA_EXT>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/author_2</ID>
      <DF lang="fr">Public cible</DF>
      <NA lang="fr">Personne qui utilise ou réutilise une ressource à des fins de production. Concept issu du LOMFR.</NA>
      <TERME>
         <INTITULE lang="fr">auteur</INTITULE>
         <ID>author</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">auteur</INTITULE>
         <ID>scolomfr-voc-011-num-002</ID>
      </TERME_TE>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/src/main/resources/scolomfr/scolomfr-v-3-1/XML/scolomfrSkosXl_n_31.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-031-num-001</ID>
      <DF lang="fr">Type de données</DF>
      <TERME>
         <INTITULE lang="fr">chaîne de caractères</INTITULE>
         <ID>scolomfr-voc-031-num-001</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-031-num-002</ID>
      <DF lang="fr">Type de données</DF>
      <TERME>
         <INTITULE lang="fr">chaîne de langage</INTITULE>
         <ID>scolomfr-voc-031-num-002</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-031-num-005</ID>
      <DF lang="fr">Type de données</DF>
      <TERME>
         <INTITULE lang="fr">date</INTITULE>
         <ID>scolomfr-voc-031-num-005</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-031-num-007</ID>
      <DF lang="fr">Type de données</DF>
      <TERME>
         <INTITULE lang="fr">durée</INTITULE>
         <ID>scolomfr-voc-031-num-007</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-031-num-008</ID>
      <DF lang="fr">Type de données</DF>
      <TERME>
         <INTITULE lang="fr">type de données structurées</INTITULE>
         <ID>scolomfr-voc-031-num-008</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-031-num-006</ID>
      <DF lang="fr">Type de données</DF>
      <TERME>
         <INTITULE lang="fr">URI (Uniform Resource Identifier)</INTITULE>
         <ID>scolomfr-voc-031-num-006</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-031-num-003</ID>
      <DF lang="fr">Type de données</DF>
      <TERME>
         <INTITULE lang="fr">vCard</INTITULE>
         <ID>scolomfr-voc-031-num-003</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-031-num-004</ID>
      <DF lang="fr">Type de données</DF>
      <TERME>
         <INTITULE lang="fr">vocabulaire</INTITULE>
         <ID>scolomfr-voc-031-num-004</ID>
      </TERME>
   </CONCEPT>
</NOMENCLATURE>
