=== j-dornbusch/scolomfr-recette/src/main/resources/scolomfr/scolomfr-v-3-1/XML/Dtd-Nomenclature.dtd
<?xml version="1.0" encoding ="ISO-8859-1"?>
<!-- DTD des fichiers XML ScoLOMFR - Canopé 20/12/2016
MAJ : 
- mise à jour en fonction de la V3.1 ; 20/12/2016 Canopé
- vérification ; ajout REMPLACE PAR et STATUS par Canopé pour validation du fichier XML des concepts dépréciés du ScoLOMFR.
NOTES :
- déclarer par <!DOCTYPE NOMENCLATURE SYSTEM "Dtd-Nomenclature.dtd">
-->

<!ELEMENT NOMENCLATURE (CONCEPT+)>
<!ELEMENT CONCEPT (ID,DF*,NA*,ORDRE?,ORIGINE?,TERME+,TERME_TE*,REMPLACE_PAR?,STATUS?,TERME_TA*,TS*)>
<!ELEMENT TERME (INTITULE,ID)>
<!ELEMENT INTITULE (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT DF (#PCDATA)>
<!ELEMENT NA (#PCDATA)>
<!ELEMENT ORDRE (#PCDATA)>
<!ELEMENT ORIGINE (#PCDATA)>
<!ELEMENT TERME_TE (INTITULE,ID)>
<!ELEMENT REMPLACE_PAR (#PCDATA)>
<!ELEMENT STATUS (#PCDATA)>
<!ELEMENT TERME_TA (INTITULE,ID)>
<!ELEMENT TS (CONCEPT+)>

<!ATTLIST INTITULE lang CDATA "fr">
<!ATTLIST DF lang CDATA "fr">
<!ATTLIST NA lang CDATA "fr">
<!ATTLIST ORDRE lang CDATA "fr">

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-2-0/XML/36.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-011</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <NA lang="fr">Concours organisé pour le recrutement de conseillers d'orientation psychologues.</NA>
      <TERME>
         <INTITULE lang="fr">concours de COP</INTITULE>
         <ID>scolomfr-voc-036-num-023</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-010</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <NA lang="fr">Concours organisé pour le recrutement de conseillers principaux d'éducation.</NA>
      <TERME>
         <INTITULE lang="fr">concours de CPE</INTITULE>
         <ID>scolomfr-voc-036-num-022</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-002</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <NA lang="fr">Concours organisé pour le recrutement de professeurs agrégés de l'enseignement du second degré.</NA>
      <TERME>
         <INTITULE lang="fr">concours de l'agrégation</INTITULE>
         <ID>scolomfr-voc-036-num-014</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-006</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <TERME>
         <INTITULE lang="fr">concours du CAER-CAPES</INTITULE>
         <ID>scolomfr-voc-036-num-018</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-004</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <TERME>
         <INTITULE lang="fr">concours du CAERPA</INTITULE>
         <ID>scolomfr-voc-036-num-016</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-005</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <TERME>
         <INTITULE lang="fr">concours du CAFEP-CAPES</INTITULE>
         <ID>scolomfr-voc-036-num-017</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-007</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <NA lang="fr">Concours organisé pour le recrutement de professeurs certifiés en éducation physique et sportive de l'enseignement du second degré.</NA>
      <TERME>
         <INTITULE lang="fr">concours du CAPEPS</INTITULE>
         <ID>scolomfr-voc-036-num-019</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-003</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <NA lang="fr">Concours organisé pour le recrutement de professeurs certifiés de l'enseignement du second degré.</NA>
      <TERME>
         <INTITULE lang="fr">concours du CAPES</INTITULE>
         <ID>scolomfr-voc-036-num-015</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-012</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <NA lang="fr">Concours organisé pour le recrutement de professeurs certifiés de l'enseignement technique.</NA>
      <TERME>
         <INTITULE lang="fr">concours du CAPET</INTITULE>
         <ID>scolomfr-voc-036-num-024</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-008</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <NA lang="fr">Concours organisé pour le recrutement de professeurs certifiés de lycée professionnel.</NA>
      <TERME>
         <INTITULE lang="fr">concours du CAPLP</INTITULE>
         <ID>scolomfr-voc-036-num-020</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-036-num-009</ID>
      <DF lang="fr">Concours de l'Éducation nationale</DF>
      <NA lang="fr">Concours organisé pour le recrutement de professeurs des écoles.</NA>
      <TERME>
         <INTITULE lang="fr">concours du CRPE</INTITULE>
         <ID>scolomfr-voc-036-num-021</ID>
      </TERME>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3-1/XML/scolomfrSkosXl_n_27.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/yes_2</ID>
      <DF lang="fr">Droit d'auteur</DF>
      <NA lang="fr">Concept issu du LOMFR.</NA>
      <ORDRE>001-oui (Sco27-DroitAuteur)</ORDRE>
      <TERME>
         <INTITULE lang="fr">oui</INTITULE>
         <ID>yes</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">oui</INTITULE>
         <ID>scolomfr-voc-027-num-001</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/no_2</ID>
      <DF lang="fr">Droit d'auteur</DF>
      <NA lang="fr">Concept issu du LOMFR.</NA>
      <ORDRE>002-non (Sco27-DroitAuteur)</ORDRE>
      <TERME>
         <INTITULE lang="fr">non</INTITULE>
         <ID>no</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">non</INTITULE>
         <ID>scolomfr-voc-027-num-002</ID>
      </TERME_TE>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/src/main/resources/scolomfr/scolomfr-v-3-1/XML/scolomfrSkosXl_n_12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE
  SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/school</ID>
      <DF lang="fr">Niveau</DF>
      <NA lang="fr">Ressource relative à l'enseignement dispensé dans les écoles maternelles, élémentaires et secondaires (collèges et lycées) (source : Code de l'éducation – articles L311-1 à L337-4)  [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
      <ORDRE>001-enseignement scolaire (Sco12-Niveau)</ORDRE>
      <TERME>
         <INTITULE lang="fr">enseignement scolaire</INTITULE>
         <ID>school</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">enseignement scolaire</INTITULE>
         <ID>scolomfr-voc-012-num-001</ID>
      </TERME_TE>
      <TS>
         <CONCEPT>
            <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-012-num-002</ID>
            <DF lang="fr">Niveau</DF>
            <NA lang="fr">Ressource relative à l'enseignement dispensé dans les écoles maternelles et élémentaires (source : Code de l'éducation – articles L321-2 à L321-4) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
            <ORDRE>02-enseignement primaire (Sco12-Niveau)</ORDRE>
            <TERME>
               <INTITULE lang="fr">enseignement primaire</INTITULE>
               <ID>scolomfr-voc-012-num-002</ID>
            </TERME>
         </CONCEPT>
      </TS>
      <TS>
         <CONCEPT>
            <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-012-num-003</ID>
            <DF lang="fr">Niveau</DF>
            <NA lang="fr">Ressource relative à l'enseignement dispensé dans les établissements secondaires (collèges et lycées) (source : Code de l'éducation – articles L331-1 à L337-4) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
            <ORDRE>03-enseignement secondaire (Sco12-Niveau)</ORDRE>
            <TERME>
               <INTITULE lang="fr">enseignement secondaire</INTITULE>
               <ID>scolomfr-voc-012-num-003</ID>
            </TERME>
         </CONCEPT>
      </TS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/higher_education</ID>
      <DF lang="fr">Niveau</DF>
      <NA lang="fr">Ressource relative à l'enseignement dispensé après l'obtention du baccalauréat ou diplôme équivalent (universités, classes préparatoires aux grandes écoles, instituts universitaires de technologie …) (source : Code de l'éducation – articles L612-1, L612-3 et L612-5) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
      <ORDRE>002-enseignement supérieur (Sco12-Niveau)</ORDRE>
      <TERME>
         <INTITULE lang="fr">enseignement supérieur</INTITULE>
         <ID>higher education</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">enseignement supérieur</INTITULE>
         <ID>scolomfr-voc-012-num-004</ID>
      </TERME_TE>
      <TS>
         <CONCEPT>
            <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-012-num-005</ID>
            <DF lang="fr">Niveau</DF>
            <NA lang="fr">Ressource relative au diplôme universitaire de premier cycle (six semestres) ou à l'enseignement dispensé lors de cette formation (source : Code de l'éducation – articles L612-2 à L612-4) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
            <ORDRE>05-licence (Sco12-Niveau)</ORDRE>
            <TERME>
               <INTITULE lang="fr">licence</INTITULE>
               <ID>scolomfr-voc-012-num-005</ID>
            </TERME>
         </CONCEPT>
      </TS>
      <TS>
         <CONCEPT>
            <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-012-num-006</ID>
            <DF lang="fr">Niveau</DF>
            <NA lang="fr">Ressource relative au diplôme universitaire de deuxième cycle (quatre semestres) ou à l'enseignement dispensé lors de cette formation (source : Code de l'éducation – articles L612-5 et L612-6) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. À ne pas confondre avec "mastère spécialisé", formation post-master propre aux écoles membres de la Conférence des grandes écoles. Concept issu du LOMFR.</NA>
            <ORDRE>06-master (Sco12-Niveau)</ORDRE>
            <TERME>
               <INTITULE lang="fr">master</INTITULE>
               <ID>scolomfr-voc-012-num-006</ID>
            </TERME>
         </CONCEPT>
      </TS>
      <TS>
         <CONCEPT>
            <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-012-num-007</ID>
            <DF lang="fr">Niveau</DF>
            <NA lang="fr">Ressource relative au diplôme universitaire de troisième cycle (trois ans) ou à l'enseignement dispensé lors de cette formation (source : Code de l'éducation – art. L612-7) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
            <ORDRE>07-doctorat (Sco12-Niveau)</ORDRE>
            <TERME>
               <INTITULE lang="fr">doctorat</INTITULE>
               <ID>scolomfr-voc-012-num-007</ID>
            </TERME>
         </CONCEPT>
      </TS>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/training</ID>
      <DF lang="fr">Niveau</DF>
      <NA lang="fr">Ressource relative au processus permettant à chaque personne, indépendamment de son statut, d'acquérir et d'actualiser des connaissances et des compétences favorisant son évolution professionnelle, ainsi que de progresser d'au moins un niveau de qualification au cours de sa vie professionnelle (source : Code du travail - art. L6111-1) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
      <ORDRE>003-formation professionnelle (Sco12-Niveau)</ORDRE>
      <TERME>
         <INTITULE lang="fr">formation professionnelle</INTITULE>
         <ID>training</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">formation professionnelle</INTITULE>
         <ID>scolomfr-voc-012-num-008</ID>
      </TERME_TE>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-012-num-010</ID>
      <DF lang="fr">Niveau</DF>
      <NA lang="fr">Ressource relative à la formation professionnelle dont l'enseignement pratique se déroule sur le lieu d'exercice de cette activité professionnelle (source : Code du travail - art. D6321-3) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
      <ORDRE>004-formation en entreprise (Sco12-Niveau)</ORDRE>
      <TERME>
         <INTITULE lang="fr">formation en entreprise</INTITULE>
         <ID>scolomfr-voc-012-num-010</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-012-num-009</ID>
      <DF lang="fr">Niveau</DF>
      <NA lang="fr">Ressource relative à la formation scolaire et professionnelle des actifs (source : Code du travail - art. L6311-1) [Disponible en ligne à l'adresse : https://www.legifrance.gouv.fr/]. Concept issu du LOMFR.</NA>
      <ORDRE>005-formation continue (Sco12-Niveau)</ORDRE>
      <TERME>
         <INTITULE lang="fr">formation continue</INTITULE>
         <ID>scolomfr-voc-012-num-009</ID>
      </TERME>
   </CONCEPT>
   <CONCEPT>
      <ID>http://data.education.fr/voc/scolomfr/concept/other</ID>
      <DF lang="fr">Niveau</DF>
      <ORDRE>006-autres (Sco12-Niveau)</ORDRE>
      <TERME>
         <INTITULE lang="fr">autres</INTITULE>
         <ID>other</ID>
      </TERME>
      <TERME_TE>
         <INTITULE lang="fr">autres</INTITULE>
         <ID>scolomfr-voc-012-num-011</ID>
      </TERME_TE>
      <TS>
         <CONCEPT>
            <ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-012-num-013</ID>
            <DF lang="fr">Niveau</DF>
            <NA lang="fr">Ressource relative à la formation propre aux écoles membres de la Conférence des grandes écoles, ou au label/diplôme délivré par ces dernières (source : Conférence des Grandes Écoles) [Disponible en ligne à l'adresse : http://www.cge.asso.fr/nos-labels/ms]. À ne pas confondre avec "master", le  diplôme universitaire de deuxième cycle (quatre semestres). Concept issu du LOMFR.</NA>
            <ORDRE>08-mastère spécialisé (Sco12-Niveau)</ORDRE>
            <TERME>
               <INTITULE lang="fr">mastère spécialisé</INTITULE>
               <ID>scolomfr-voc-012-num-013</ID>
            </TERME>
            <TERME_TE>
               <INTITULE lang="fr">mastère</INTITULE>
               <ID>scolomfr-voc-012-num-014</ID>
            </TERME_TE>
         </CONCEPT>
      </TS>
   </CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/src/main/resources/scolomfr/scolomfr-v-3/XML/13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/creator</ID>
<DF lang="fr">Rôle (métadonnées)</DF>
<NA lang="fr">Personne ou organisme responsable de la création de la fiche descriptive. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">créateur</INTITULE>
<ID>creator</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">créateur</INTITULE>
<ID>scolomfr-voc-013-num-001</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/validator</ID>
<DF lang="fr">Rôle (métadonnées)</DF>
<NA lang="fr">Personne ou organisme responsable de la validation de la fiche descriptive. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">validateur</INTITULE>
<ID>validator</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">validateur</INTITULE>
<ID>scolomfr-voc-013-num-002</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/validator</ID>
<DF lang="fr">Rôle (métadonnées)</DF>
<NA lang="fr">Personne ou organisme responsable de la validation de la fiche descriptive. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">validateur</INTITULE>
<ID>validator</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">validateur</INTITULE>
<ID>scolomfr-voc-013-num-002</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/creator</ID>
<DF lang="fr">Rôle (métadonnées)</DF>
<NA lang="fr">Personne ou organisme responsable de la création de la fiche descriptive. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">créateur</INTITULE>
<ID>creator</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">créateur</INTITULE>
<ID>scolomfr-voc-013-num-001</ID>
</TERME_TE>
</CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/doc/scolomfr/scolomfr-v-3/XML/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/learner</ID>
<DF lang="fr">Public cible</DF>
<NA lang="fr">Personne qui exploite, travaille avec la ressource afin d'apprendre quelque chose. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">apprenant</INTITULE>
<ID>learner</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">apprenant</INTITULE>
<ID>scolomfr-voc-011-num-003</ID>
</TERME_TE>
<TERME_TA>
<INTITULE lang="fr">élève à besoins éducatifs spécifiques</INTITULE>
<ID>scolomfr-voc-021-num-0008</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">élève</INTITULE>
<ID>scolomfr-voc-021-num-0007</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">étudiant</INTITULE>
<ID>scolomfr-voc-021-num-0012</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/author_2</ID>
<DF lang="fr">Public cible</DF>
<NA lang="fr">Personne qui utilise ou réutilise une ressource à des fins de production. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">auteur</INTITULE>
<ID>author</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">auteur</INTITULE>
<ID>scolomfr-voc-011-num-002</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/teacher</ID>
<DF lang="fr">Public cible</DF>
<NA lang="fr">Personne responsable par les activités de transmission des connaissances et compétences dans le cadre de la "formation tout au long de la vie". Inclut les tuteurs. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">enseignant</INTITULE>
<ID>teacher</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">enseignant</INTITULE>
<ID>scolomfr-voc-011-num-001</ID>
</TERME_TE>
<TERME_TA>
<INTITULE lang="fr">enseignant des disciplines</INTITULE>
<ID>scolomfr-voc-021-num-0009</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">enseignant documentaliste</INTITULE>
<ID>scolomfr-voc-021-num-0010</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">enseignant du supérieur</INTITULE>
<ID>scolomfr-voc-021-num-0011</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">professeur des écoles</INTITULE>
<ID>scolomfr-voc-021-num-0023</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/manager</ID>
<DF lang="fr">Public cible</DF>
<NA lang="fr">Personne qui gère ou déploie des ressources. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">gestionnaire</INTITULE>
<ID>manager</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">gestionnaire</INTITULE>
<ID>scolomfr-voc-011-num-004</ID>
</TERME_TE>
<TERME_TA>
<INTITULE lang="fr">personnel de direction</INTITULE>
<ID>scolomfr-voc-021-num-0019</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/manager</ID>
<DF lang="fr">Public cible</DF>
<NA lang="fr">Personne qui gère ou déploie des ressources. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">gestionnaire</INTITULE>
<ID>manager</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">gestionnaire</INTITULE>
<ID>scolomfr-voc-011-num-004</ID>
</TERME_TE>
<TERME_TA>
<INTITULE lang="fr">personnel de direction</INTITULE>
<ID>scolomfr-voc-021-num-0019</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/author_2</ID>
<DF lang="fr">Public cible</DF>
<NA lang="fr">Personne qui utilise ou réutilise une ressource à des fins de production. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">auteur</INTITULE>
<ID>author</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">auteur</INTITULE>
<ID>scolomfr-voc-011-num-002</ID>
</TERME_TE>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/teacher</ID>
<DF lang="fr">Public cible</DF>
<NA lang="fr">Personne responsable par les activités de transmission des connaissances et compétences dans le cadre de la "formation tout au long de la vie". Inclut les tuteurs. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">enseignant</INTITULE>
<ID>teacher</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">enseignant</INTITULE>
<ID>scolomfr-voc-011-num-001</ID>
</TERME_TE>
<TERME_TA>
<INTITULE lang="fr">enseignant des disciplines</INTITULE>
<ID>scolomfr-voc-021-num-0009</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">enseignant documentaliste</INTITULE>
<ID>scolomfr-voc-021-num-0010</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">enseignant du supérieur</INTITULE>
<ID>scolomfr-voc-021-num-0011</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">professeur des écoles</INTITULE>
<ID>scolomfr-voc-021-num-0023</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/learner</ID>
<DF lang="fr">Public cible</DF>
<NA lang="fr">Personne qui exploite, travaille avec la ressource afin d'apprendre quelque chose. Concept issu du LOMFR.</NA>
<TERME>
<INTITULE lang="fr">apprenant</INTITULE>
<ID>learner</ID>
</TERME>
<TERME_TE>
<INTITULE lang="fr">apprenant</INTITULE>
<ID>scolomfr-voc-011-num-003</ID>
</TERME_TE>
<TERME_TA>
<INTITULE lang="fr">élève à besoins éducatifs spécifiques</INTITULE>
<ID>scolomfr-voc-021-num-0008</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">élève</INTITULE>
<ID>scolomfr-voc-021-num-0007</ID>
</TERME_TA>
<TERME_TA>
<INTITULE lang="fr">étudiant</INTITULE>
<ID>scolomfr-voc-021-num-0012</ID>
</TERME_TA>
</CONCEPT>
</NOMENCLATURE>

=== j-dornbusch/scolomfr-recette/src/main/resources/scolomfr/scolomfr-v-3/XML/46.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NOMENCLATURE SYSTEM "Dtd-Nomenclature.dtd">
<NOMENCLATURE>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-003</ID>
<DF lang="fr">Type de distribution</DF>
<TERME>
<INTITULE lang="fr">téléchargeable</INTITULE>
<ID>scolomfr-voc-046-num-003</ID>
</TERME>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-001</ID>
<DF lang="fr">Type de distribution</DF>
<TERME>
<INTITULE lang="fr">en ligne</INTITULE>
<ID>scolomfr-voc-046-num-001</ID>
</TERME>
<TERME_TA>
<INTITULE lang="fr">support numérique en ligne</INTITULE>
<ID>scolomfr-voc-043-num-023</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-002</ID>
<DF lang="fr">Type de distribution</DF>
<TERME>
<INTITULE lang="fr">papier</INTITULE>
<ID>scolomfr-voc-046-num-002</ID>
</TERME>
<TERME_TA>
<INTITULE lang="fr">document imprimé</INTITULE>
<ID>scolomfr-voc-043-num-016</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-001</ID>
<DF lang="fr">Type de distribution</DF>
<TERME>
<INTITULE lang="fr">en ligne</INTITULE>
<ID>scolomfr-voc-046-num-001</ID>
</TERME>
<TERME_TA>
<INTITULE lang="fr">support numérique en ligne</INTITULE>
<ID>scolomfr-voc-043-num-023</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-002</ID>
<DF lang="fr">Type de distribution</DF>
<TERME>
<INTITULE lang="fr">papier</INTITULE>
<ID>scolomfr-voc-046-num-002</ID>
</TERME>
<TERME_TA>
<INTITULE lang="fr">document imprimé</INTITULE>
<ID>scolomfr-voc-043-num-016</ID>
</TERME_TA>
</CONCEPT>
<CONCEPT>
<ID>http://data.education.fr/voc/scolomfr/concept/scolomfr-voc-046-num-003</ID>
<DF lang="fr">Type de distribution</DF>
<TERME>
<INTITULE lang="fr">téléchargeable</INTITULE>
<ID>scolomfr-voc-046-num-003</ID>
</TERME>
</CONCEPT>
</NOMENCLATURE>
